name: Overleaf Progress Track

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  texcount:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install texlive(basic)
        run: sudo apt install texlive
      - name: Install texcount
        run: sudo apt-get install -y texlive-extra-utils
      - name: Install Slack python SDL
        run: |
          pip install slack-sdk
          pip install aiohttp
      - uses: actions/checkout@v2
      - name: Run Python
        run: sh updateProgress.sh
      - name: Commit progress
        run: |
          git config --global user.name 'Your git hub name'
          git config --global user.email 'Your git email'
          git add .
          git commit -am "Generated progress report"
          git push